system:
    bin_directory: ""
    generate_directories: False
    run_codes: True
    on_hpc: True
    pci_version: default

hpc:
    partition: standard
    nodes: 10
    tasks_per_node: 32
    submit_job: False

atom:
    name: Fe16+
    isotope: 56
    include_breit: True
    code_method: ci

# Parameters used by basis programs
basis:
    cavity_radius: 5
    diagonalized: False
    orbitals:
        core: 1s 2s 2p
        valence: 3s 3p 3d 4s 4p 4d 4f 5g
        order: 2p 3d / 3s 3p / 4s 4p 4d 4f 5g
        custom: [
            4s from hfd,
            4p from hfd,
            4d from hfd,
            4f from hfd,
            5g from 3p
        ]
        nmax: 15
        lmax: 4

# Parameters used by add program
add:
    # Lists of even and odd parity reference configurations
    ref_configs:
        odd: [1s2 2s2 2p5 3s1, 1s2 2s2 2p5 3d1, 1s2 2s1 2p6 3p1]
        even: [1s2 2s2 2p6,
               1s2 2s2 2p5 3p1,
               1s2 2s1 2p6 3s1]
    basis_set: 8spdfg
    orbitals:
        core:
        active: [
            1s: 0 2,
            2s: 0 2,
            2-7p:  0  6,
            3-7d:  0  6,
            4-7f:  0  6,
            5-7g:  0  6,
            ]    
    excitations:
        single: True
        double: True
        triple: False


# Parameters used by conf program
conf:
    odd:
        J: 1
        JM: 1
        J_selection: True
        num_energy_levels: 5
        num_dvdsn_iterations: 100
    even:
        J: 0.0
        JM: 0.0
        J_selection: False
        num_energy_levels: 5
        num_dvdsn_iterations: 100
    include_lsj: True
    write_hij: False

    
# Optional parameters
optional:
    qed:
        include: False

    isotope_shifts: 
        include: False
        K_is: 0
        C_is: 0
